backend:
    name: git-gateway
    branch: main

media_folder: "images"
public_folder: "/images"

collections:
    - name: "recipes"
      label: "מתכונים"
      folder: "data/recipes"
      create: true
      format: "json"
      slug: "{{slug}}"
      fields:
          - { label: "שם המתכון", name: "title", widget: "string" }
          - { label: "תמונה", name: "image", widget: "image" }
          - { label: "מצרכים", name: "ingredients", widget: "list", field: { label: "מצרך", name: "item", widget: "string" } }
          - { label: "אופן הכנה", name: "instructions", widget: "text" }

    - name: "products"
      label: "מוצרים"
      folder: "data/products"
      create: true
      format: "json"
      slug: "{{slug}}"
      fields:
          - { label: "שם המוצר", name: "name", widget: "string" }
          - { label: "תיאור", name: "description", widget: "text" }
          - { label: "מחיר", name: "price", widget: "string" }
          - { label: "תמונה", name: "image", widget: "image" }
          - { label: "במלאי", name: "inStock", widget: "boolean" }
